### ISSUE TITLE
PyPlex resurrection

### ISSUE THREAD

**Issue by dalehamel** [RasPlex/RasPlex#105]
Before rasplex, there was pyplex. It offers similar functionality to chromecast.

We could fairly easily bundle pyplex into rasplex, and select which payload to use via a kernel arg.

All we would need to do is make OE packages for OMXplayer and pyplex, and add support to busybox for selecting which init script to load dynamically.

**Comment by NedtheNerd** [comment]
@dalehamel 

Is this still relevant to Rasplex, if not can you please close this issue.

**Comment by derekcentrico** [comment]
I realize I'm relatively new to this scene, however let me annoy you if I may.

Pyplex is useful for 256mb Pis sure.  However, the same casting functionality from the Plex app on any device works just fine iwth Rasplex as it stands.

So, it may be much more preferable to have separate branches with a Rasplex "lite" variant using Pyplex for older hardware.  This would help alleviate any unforeseen and persistent bugs from merging the two for a general release?

**Comment by NedtheNerd** [comment]
Closing issue.
