### ISSUE TITLE
Double subtitle appear when using transcoding

### ISSUE THREAD

**Issue by liiight** [RasPlex/RasPlex#137]
When I force transcoding, and also enable "Always transcode subtitles", I see two sets of subtitles. One that is being transcoded, and another set which is the same on that I see when using direct play.
Changing the subtitles setting during playback affect only the transcoded ones, not the "regular" ones.

Rasplex 9.9.20
512 Pi
Ethernet
Rasplex instalelr on Win
PMS 0.9.9.2

Not sure logs are relevant but will provide if needed.
will also add a image later.

**Comment by NedtheNerd** [comment]
Can you test in latest release 0.5.0 and advise, should be fixed.
