### ISSUE TITLE
0.4.0rc1 - selection of precaching servers unclear

### ISSUE THREAD

**Issue by norbusan** [RasPlex/RasPlex#158]
The list of servers to precache does not have a clear indication which one is selected. No tickmark. The color changes, but that does also happen when you move the selection, so it is very unclear whether precache has been activated or not. Trial and error.

Would be nice to have check boxes.

Thanks

Norbert

**Comment by NedtheNerd** [comment]
This was fixed in default screen several releases ago, closing issue.
