### ISSUE TITLE
Changing device name not working - 0.4.0rc1

### ISSUE THREAD

**Issue by wabee** [RasPlex/RasPlex#174]
I have two Pis on my network and need to change the default name of one of them. Tried changing from rasplex to rasplex1 in the GUI. Does not actually change anything though. Unit still comes up as rasplex in airplay menu. Also unit is not visible  on network when samba is enabled. Can manually attach to volume using actual ip though.

**Comment by martylavender** [comment]
This isn't working. I've changed the Rasplex name under System. The iOS app just shows Raslpex as the name for both PIs

**Comment by NedtheNerd** [comment]
Change the device name in Preferences, System, Services, Device name.
