### ISSUE TITLE
0.4.0-rc2 Bluetooth files not available after first play

### ISSUE THREAD

**Issue by guydev** [RasPlex/RasPlex#212]
I thought to test the Bluetooth capabilities of the Raspberry Pi and Rasplex.
I plugged in a USB Bluetooth adapter, but this was not recognised by Rasplex and in Bluetooth Settings in 0.4.0-rc2.

I therefore swapped to the SD card containing my 9.9.19 installation. Bluetooth is recognised and I was able to copy a video file from my phone to the Pi. Rasplex then asked if I wanted to play it. Yes it played.

However after playing one cannot locate the file to play again. I therefore connected to  the Pi using SSH and see that the file is in storage/downloads folder.

So I am not sure how useful Bluetooth is to have in Rasplex... unless there is some way in plex to access files on SD card or USB..
 
I see that the file i

**Comment by NedtheNerd** [comment]
Only Bluetooth keyboards supported in 1.0.0, closing issue.
