### ISSUE TITLE
Can't connect to WiFi: Invalid Arguments

### ISSUE THREAD

**Issue by silentsnake14** [RasPlex/RasPlex#225]
Using 0.4.0-rc3 on a Raspberry Pi 512 MB with Edimax Wireless 802.11b/g/n nano USB Adapter I can't connect to my WiFi. Only message I get is "Invalid Arguments".

Tested on two devices (Separate Raspberry Pi's, Wireless Adapters and SD cards) with a clean install on each.

Signal strength is at 100 %, network is working fine on all other devices and both Raspberry Pi's worked without problems on Xbian and Arch Linux.

Given advice in another Issue (Use shorter passphrase) is not possible for me.

**Comment by NedtheNerd** [comment]
@silentsnake14 Is this still an issue in 0.5.1.

If not can you please close this issue.

**Comment by trondvh** [comment]
Still the same issue on 0.5.1 on pi2.

**Comment by NedtheNerd** [comment]
Can you test on 0.7.1, if no feedback issue will be closed.

**Comment by Qrbaker** [comment]
To jump on this, I'm trying to use connman over ssh to connect to an EAP network. Perhaps if a config file could be created with VIM and connman could pull from that to prevent the timeout issue...?

**Comment by NedtheNerd** [comment]
No further feedback since March, closing issue.

**Comment by falahati** [comment]
Still an issue Ned,

**Comment by GarlandM** [comment]
Can confirm, still had this issue.

**Comment by johnnyKaZOO** [comment]
I can also confirm this is still an issue. My password is 36 characters long and it takes ages to type it in on a TV remote, after 4 attempts I finally managed to do it quick enough. 

Would it not be possible to start the connection attempt after the user has typed the password? You can take as long as you want then.

**Comment by D0048** [comment]
Can confirm that this issue still exists.

**Comment by cpfaff** [comment]
I have this with the latest release and an edimax wifi dongle.

**Comment by cpfaff** [comment]
I have this now with the latest release and an edimax wifi dongle.

**Comment by stdclass** [comment]
Have the same problem. Raspberry Pi 3 with the latest 2017-11-29-raspbian-stretch image.

**Comment by cpfaff** [comment]
You can try to use the console as I did. Ssh to the machine and use connman. That works! That way you also get it working remembering multiple connections which never worked for me from the UI.

https://gist.github.com/maoueh/8260199
