### ISSUE TITLE
Build not working properly with new Unitary tests

### ISSUE THREAD

**Issue by LongChair** [RasPlex/RasPlex#230]
I think i found the issue. When linking the Test stuff it seems we're missing a library:

/home/plexuser/OpenELEC.tv/build.rasplex-RPi.arm-devel-release/toolchain/lib/gcc/armv6zk-openelec-linux-gnueabi/4.7.3/../../../../armv6zk-openelec-linux-gnueabi/bin/ld: cannot find -lgtest

@dalehamel : maybe you can heck how to add this lib into the dependencies for plex ? :)

**Comment by NedtheNerd** [comment]
Closing issue
