### ISSUE TITLE
Enable PHT volume amplification for rasplex?

### ISSUE THREAD

**Issue by ledge74** [RasPlex/RasPlex#246]
Hi,

I have noticed that in rasplex, the volume amplification function is disabled.
Would it be possible to enable it? This might be useful for those (like me) that have the raspberry connected to an amp through the 3.5mm jack output and need to put the volume at the maximum to have an "ok" level of sound with a lot of interferences. 

Thank you guys !

**Comment by dalehamel** [comment]
bump is this still an issue in 0.5.1?

**Comment by NedtheNerd** [comment]
Works in 0.5.1, use + and minus buttons, tested.
