### ISSUE TITLE
On screen keyboard not working correctly

### ISSUE THREAD

**Issue by siavash8** [RasPlex/RasPlex#252]
Size of Raspberry Pi: 512
Type of SD card: class 10, came included in the Raspberry Pi package I bought from Amazon
Internet connection type: Ethernet
Version of RasPlex: 0.4.0-rc3
Version of PlexServer: 0.9.9.7 (Running on Linux Mint 16)
How did you install rasplex? Initially flash on SD card on a Linux machine using the file provided on the website, then updated to rc3 from the System menu.
Logfile: http://pastebin.com/HK37zaXP
Best description you can give of the problem: (video of the bug here: http://youtu.be/Ryg7IUAWVA4 I tried my best to show the remote key presses while filming the screen, I don't know how clear it is) While trying to use the on-screen keyboard (e.g. entering an IP for the server, or entering a time for hard drive sleep), I'm unable to navigate to the Done button at the bottom using my TV remote. The navigation is not what it's supposed to be, for example sometime I press up and the highlighted key doesn't go up, but disappears. It can be figured out though. Strangely, I have to press pause on my remote for the on-screen keyboard to close, and that doesn't always work (as in the video). But no matter what I do, I can't get to the done key to save the number.
Steps to reproduce: Go to the any settings (Preferences or RasPlex Settings) and try to enter a number somewhere.

**Comment by NedtheNerd** [comment]
This was fixed in 0.4.1, closing issue.
