### ISSUE TITLE
0.4.0-rc3 SSA/ASS subtitles not working

### ISSUE THREAD

**Issue by mkrle** [RasPlex/RasPlex#258]
SSA/ASS subtitles do not work in RasPlex 0.4.0-rc3 while they work normally in PHT. This is 100% reproducible, apart from regular movies and subs I've reproduced it with a 300MB SD mp4/h264/aac test video file with test one line test subs. 

I'm pretty sure HW specs are not important here but here it goes: 512MB model B, stock (raspberry branded) SD card, Ethernet, installed from GUI, 1A PSU, LAN connected PMS 0.9.9.7.429-f80a8d6 on an i7-3770k Win8.1 PC.

grep -i error http://pastebin.com/gSkMfVBe
tail -n 40 http://pastebin.com/T72QjfC6 (doubt there's anything here)
a snip from cat which should be interesting http://pastebin.com/5p0mk8P3 (around the SSA errors)

Needless to say, SRT, SUBRIP and VOBSUB work perfectly in both RasPlex and PHT.

**Comment by NedtheNerd** [comment]
No further comment from author, closing.
