### ISSUE TITLE
RasPlex only handles 5.1 audio that can be passed-through in bitstream form - rc4 and below

### ISSUE THREAD

**Issue by thestagemanager** [RasPlex/RasPlex#268]
Was touched on a little bit in #166, but when playing a video that has FLAC or AAC 5.1 audio, the output from the Pi is LPCM 2.0 instead of 5.1 (#166 was mainly focused on a separate issue, so seemed worth opening a dedicated item for this).  

Similarly, if you disable passthrough for a video with either AC3 or DTS 5.1 audio, the output from the Pi is again LPCM 2.0, even if you've set the number of output channels to 5.1.

So the problem seems to be that RasPlex can't currently output 5.1 channel audio except as a passed-through bitstream.

If there were some way to make the transcoder kick on when multichannel audio formats, like FLAC or AAC, are detected and convert them to AC3 or DTS on-the-fly, RasPlex could then just pass the bitstreams through to the AV receiver, preserving 5.1 playback.

Similarly, I saw some experimental builds of OpenELEC back when I first started playing around with this that were actually getting the LPCM output to switch over to 5.1 as needed.  That was a while back, though, and I don't know that whatever was making that happen ever made it into their stable builds or not.

**Comment by dalehamel** [comment]
This will likely be resolved by 0.6.1

**Comment by glamorous** [comment]
Is there a ETA for version 0.6.1? It's a little bit a deal breaker for now...

**Comment by dalehamel** [comment]
As soon as we can make sure it's stable, I'd say a couple weeks

**Comment by glamorous** [comment]
That would be great news! Looking forward to it...

**Comment by NedtheNerd** [comment]
Fixed in next release. Closing.

**Comment by derekcentrico** [comment]
Just saw you closed this NedtheNerd!  Awesome!!!  Cannot wait! :+1:
