### ISSUE TITLE
Windows Media Remote not working in 0.4.0-rc4

### ISSUE THREAD

**Issue by bmccart** [RasPlex/RasPlex#269]
Running a Raspberry Pi Model B Booting from a USB Stick using the latest release 0.4.0-rc4

My Windows Media Remote still isn't recognized. It does the same hang as soon as you try to press a button. The light on the IR stays on but it doesn't seem to control anything. I believe there was some mention that someone had this working on rc2? I haven't had any luck. I still have the same issue. For the record I tested it on all revs to date.

All in all this is the most amazing, rock solid release of RasPlex to date! Keep up the good work!

**Comment by NedtheNerd** [comment]
Can you check in latest release 0.5.0 and advise.

**Comment by bmccart** [comment]
Just tested it. Issue persists

Also attempted booting, unplugging IR and then reconnecting it. 

That also did not resolve the issue

**Comment by bmccart** [comment]
I can confirm that WMR is now working in 0.6!

Thanks guys!
