### ISSUE TITLE
ASS subtitle framerate

### ISSUE THREAD

**Issue by Deathspike** [RasPlex/RasPlex#271]
In RasPlex 0.4.0-rc4, ASS subtitles seem to be using a different frame-rate and/or stuttering due to RasPlex being unable to keep up. This often causes subtitles to appear too late (up to 2 seconds delay, at times, when at other times there is none). Text that is supposed to be moving with the screen makes the issue especially notable.

For reproduction purposes, I recommend using an anime series. Most fansub groups use MKV/ASS to colorize subtitles according to the speaking character. When Japanese signs appear, e.g. shop and/or school names, a text often appears with the translation. 9/10 times the image will be moving, and in PHT the text will move accordingly at nearly the correct framerate.

I have not used a previous version of RasPlex. RasPBMC does handle the subtitles properly. Did I miss some information? Please let me know, I'll get back with the requested details a.s.a.p.

**Comment by NedtheNerd** [comment]
No further comment from author, closing.

**Comment by Robpollard** [comment]
Sorry for reopening, but I'm having problems with *.ass subs embedded into Anime-MKVs as well - on a Raspberry Pi 2 @ Rasplex 0.6.0. The srt subs are displayed fine, but with maybe half of the lines the last third of the line is an unreadable mess (supposedly because the processor can't keep upt?
