### ISSUE TITLE
Stuttering/pauses during playback

### ISSUE THREAD

**Issue by yogeshdengle** [RasPlex/RasPlex#273]
Hi,

I have RC4 on a 512MB Pi. 
Before the upgrade from RC2 to RC4 i was getting consistent stuttering every few minutes, irrespective of the kind of file I was playing. 
Did a hard reset and now I do not have consistent stuttering but every one in a while I do get errors:
I see these warning in the log file:

12:42:55 T:3046612992  NOTICE: GL: NPOT texture support detected
12:43:17 T:2582639712 WARNING: CRenderManager::FlipPage - timeout waiting for flip to complete
12:43:28 T:2582639712 WARNING: Previous line repeats 1 times.
12:43:28 T:2582639712 WARNING: CRenderManager::FlipPage - timeout waiting for previous frame
12:43:32 T:2582639712 WARNING: CRenderManager::FlipPage - timeout waiting for flip to complete
12:43:33 T:2582639712 WARNING: CRenderManager::FlipPage - timeout waiting for previous frame
12:48:36 T:2582639712 WARNING: Previous line repeats 2 times.
12:48:36 T:2582639712 WARNING: CRenderManager::FlipPage - timeout waiting for flip to complete
13:01:58 T:2591028320   ERROR: Error: Requested setting (pvrplayback.scantime) was not found.  It must be case-sensitive
13:02:03 T:2582639712 WARNING: CRenderManager::FlipPage - timeout waiting for flip to complete

And free memory is this:
RasPlex:~/.plexht/temp # free -m
             total         used         free       shared      buffers
Mem:           300          277           22            0            2
-/+ buffers:                275           25
Swap:          249            7          242
RasPlex:~/.plexht/temp #

Any hints as to what might be the problem.
Also I was not able to figure out the info overlay that everyone talks about, how do i activate that to get info.

Thanks!

**Comment by shoghicp** [comment]
This affects me on RasPlex 0.7.0 on a Raspberry Pi B+, only with music. Depending on the sound file it skips more or less often, doesn't happen if it is a video (even a black video with the same track in a channel)
