### ISSUE TITLE
Dual Audio support

### ISSUE THREAD

**Issue by Wouter0100** [RasPlex/RasPlex#278]
I was looking in the https://github.com/RasPlex/plex-home-theatre/blob/rasplex-dev/xbmc/cores/omxplayer/OMXAudio.cpp file and in the same file in the xbmc repostory (https://github.com/xbmc/xbmc/blob/9a8c117bf6bc9c5a7c9ea1bd3648165dcd03bb47/xbmc/cores/omxplayer/OMXAudio.cpp), but it seems like the plex-home-theatre one is missing the dualaudio functionality. Is there any way to add this to Rasplex?

Currently I've attached my stereo (for music) to my raspberry and my television (for movies and photos) through HDMI. But I'd like to active this "dualaudio" functionality so I don't need to switch the raspberry all the time between HDMI and analog.. Also, I'll think this would be a handy functionality for Rasplex for other users.

**Comment by yannlet** [comment]
Any news on dual audio ? It is part of this release ?
Thanks !

**Comment by NedtheNerd** [comment]
Not part of this release, requires OpenELEC 4.x or 5.x, awaiting upstream merge of PHT with Helix.

**Comment by dalehamel** [comment]
We are merging OE5 for our next release, 0.6.0 and updating OMX player in 0.6.1 this should likely fix the problem. Stay tuned.

**Comment by NedtheNerd** [comment]
Fixed in next release.
