### ISSUE TITLE
Unknown Audio Codec - A52 (AC3) Audio ( Ray Donovan Blu-ray Rip)

### ISSUE THREAD

**Issue by alxscott** [RasPlex/RasPlex#284]
Details:
512 Rev B Pi
SDHC Class 10
Ethernet Connection
OS X Installer
PMS Version: 0.9.9.12.504-3e7f93c ( unRAID v6 Beta 5 Server)

Log Files:
Rasplex Log: http://pastebin.com/yhKH9jJY
Episode XML : http://pastebin.com/Y2pXEuah

Description of Bug:
Ripped Bluray using MakeMKV 1.9.11 using same settings as other discs which play fine. There are two audio codecs in the stream, TrueHD 5.1 which i know can cause issues, and AC3 5.1 ( ffprobe shows the AC3 track as A52).

When attempting to play the AC3 track Rasplex reports unknown codec; transcoding. My server is only an Atom so it struggles like hell. My issue is, as far as i believe, it shouldn't be transcoding AC3? Everything else I have in AC3 plays fine...

Many Thanks for any help or advice!
Alex

**Comment by dalehamel** [comment]
Is this still an issue in 0.5.1?

**Comment by alxscott** [comment]
I remuxed the few files I had an issue with so I couldn't say anymore if I'm honest!

**Comment by NedtheNerd** [comment]
Closed
