### ISSUE TITLE
Rasplex hangs trying to play from an non existend server

### ISSUE THREAD

**Issue by pziarsolo** [RasPlex/RasPlex#289]
I have the server in a mac mini and sometimes it goes to sleep.
I have rasplex 0.4 rc04 with precaching.

If the server is sleep and try to play any content from it, rasplex stops responding and the unique way to get it back is restarting manually(unplugging).

It shouldn't stop responding but show some message.

Thanks!
Peio

**Comment by NedtheNerd** [comment]
Can you check this in latest release 0.5.0 and advise.

**Comment by dalehamel** [comment]
Closing as stale issue.
