### ISSUE TITLE
Dual audio output

### ISSUE THREAD

**Issue by bohemier** [RasPlex/RasPlex#297]
Hi everyone,

As per https://github.com/RasPlex/RasPlex/issues/100 , I would like to reopen this request. I named it properly so others can find it. 

The idea is to enable the dual audio output feature that is already present in Openelec as described in the original issue. The feature is enabled within guisettings.xml in &lt;audiooutput&gt; section:

&lt;audiooutput&gt;
&lt;dualaudio&gt;true&lt;/dualaudio&gt;
&lt;/audiooutput&gt;

As stated in this other post https://forums.plex.tv/index.php/topic/112864-dual-audio-option/ the guisettings.xml file gets reverted back upon boot, also when issuing a 'killall plexhometheater' so it is impossible to test. 

If openelec supports this, it should be fairly easy to implement I think? Is there way to bypass the reverting of the audiooutput section?

Thanks

Raspberry pi Model B 512, Rasplex 0.4.0-rc3, Plexpass

**Comment by NedtheNerd** [comment]
Fixed in next release.

**Comment by bohemier** [comment]
Wonderful! Thanks :)
