### ISSUE TITLE
Strang "hang", even with ssh

### ISSUE THREAD

**Issue by glamorous** [RasPlex/RasPlex#303]
Hi,

After installing and trying out the new 4.1 software (had it once or twice with older version too). I've come to a point where rasplex "hangs" and doesn't react on a remote. When I try to SSH to it, I can access it, but when i try to "halt now", it just hangs more and I can't connect to it anymore trough ssh and id didn't shutdown/restart. The only thing I can do it power off trough the socket.

Is this typical for the raspberry pi or for rasplex?

Thanks!

**Comment by NedtheNerd** [comment]
No further follow up, closing issue.
