### ISSUE TITLE
Playback randomly stops, throws back to main screen

### ISSUE THREAD

**Issue by GarethDPhillips** [RasPlex/RasPlex#307]
I am getting random playback stops, once, maybe twice per movie. No choppiness or slowness beforehand, just an abrupt stop and back to main screen. I can usually resume instantly, but sometimes am forced to start the movie from the beginning.

Only recently installed Rasplex, exact hardware used previously with RaspBMC with no issues. Pi and Server are hard wired. 

Generally throwing movie to the screen from iOS or Android app.

Server and Pi on very latests versions (PlexPass)

**Comment by NedtheNerd** [comment]
Can you test this issue with latest release 0.5.0 and advise.

**Comment by dasRicardo** [comment]
Hello,
first thx for the great work on rasplex. I facing the same problem with every movie. After round about 50 up to 60 minutes the movie stop and i jump back to movie description screen where i start playing the movie. There are no signs that indicates a stop of the movie struggling or something. My setup: Rasp. B 512mb, all movies will transcode (force that) subtitles also. Rasplex and server are connected with wire to the router.

**Comment by GarethDPhillips** [comment]
I've found things much better since the latest release.

**Comment by NedtheNerd** [comment]
@dasRicardo 
Have you overlocked your Pi, if not suggest that you do, information on forum.
Have you tried turning off forced transcoding and using DirectPlay?

Regards

**Comment by dasRicardo** [comment]
@NedtheNerd 
No for both questions. The problem with directplay in my setup is that FullHD Material always struggle in playing. Hmm you think it's a problem with the plex server instead of the client?

**Comment by GarethDPhillips** [comment]
You will probably find that direct playing full HD material will give you problems, unless you are passing DTS or Dolby digital audio to an external receiver. If you are relying on the Pi to convert digital audio to Stereo for your TV, for example, you will probably be hurting the CPU too much. 

I bought a sound bar that can decode DD and DTS, and enabled pass through of the audio for external processing, and playback is generally great.

**Comment by GarethDPhillips** [comment]
You may therefore find that transcoding is better, as it will relieve some of the strain on the limited CPU of the Pi, so long as your server has enough CPU grunt to do this (check task manager, if the CPU is at 100% during transcode, you can assume it doesn't)

**Comment by dasRicardo** [comment]
So i can serve 3 devices with fullHD transcoded material at the same time without problems i will test it with my android tablets if the same happens

**Comment by dalehamel** [comment]
Is this still an issue in 0.5.1, or on RPi2?

**Comment by dasRicardo** [comment]
No is not a rasplex problem. The problem was my server setup. I transcode my movies and use as temp transcode folder a ramdisk of 3GB size. But the plexserver remove the tempfiles only if the movie stops or is finished so after round about 50 up to 60 min depends on the movie quality my ramdisk is full and the movie stops playing :) That's all :)

**Comment by NedtheNerd** [comment]
Issue now closed.
