### ISSUE TITLE
near impossible to "skip back"

### ISSUE THREAD

**Issue by mysteryman69** [RasPlex/RasPlex#309]
There is a fastforward/rewind, but there is also a skip x time option. These are programmed to the directional keys on the remote/keyboard while playing media. I believe up and down are like 15  minutes (which is a really long time on short shows); left and right is 30s or 1 minute...We'll assume those are the times, since it doesn't really matter, one is longer one is shorter. The long one is simply too long, and I basically never use it.

Back to the bug... on pc, when you're watching a video and miss something you want to rewatch, you can press left 2 times. It quickly rebuffers and starts playing from T- (n*2). If you've missed a bunch of it, like 5 or 10 minutes because you fell asleep while watching it... you press it a bunch of times...this works the same for going forward past a unwanted section of video.

On rasplex, however, this is very difficult to do effectively. When you press the button the first time, it starts buffering video for 30 seconds in past... but then won't respond to additional presses until it has been buffered. 
example... 
timestamp 5m, press left = timestamp 4:30
timestamp 5m. press left twice = timestamp 4:30
timestamp 5m press left 25 times = timestamp 4:30
timestamp 5m press left. wait 5 seconds for buffering, press left again = timstamp 4m

Rasplex does appear to "respond" to the second press. It's not locked up. What appears to be happening is that it recalculates the time based on the old timestamp instead of from the currently  caching (new) timestamp. This should be easy enough to fix if my assumption is correct.

**Comment by NedtheNerd** [comment]
Little Skip forwards and backwards and Big Skip forwards and backwards working in 0.5.1 release on both RPi1 and RPi2.

Closing issue.
