### ISSUE TITLE
Hangs, no subtitles, ...

### ISSUE THREAD

**Issue by glamorous** [RasPlex/RasPlex#314]
Serial number of your pi: not known for the moment
Crash ID: No crash id received
Size of Raspberry Pi: 512
Type of SD card: SDHC class 10
Internet connection type: Ethernet but PMS is Wifi for the moment
Version of RasPlex: 0.4.1
Log files:
- http://pastebin.com/m4VQUYJc
- http://pastebin.com/cgUmL9iU
How did you install rasplex: auto-update

Last evening I wanted to watch a movie, I had some problems with the "trailers" before the movie, just let the system hang, I restarted a couple of times. The first time I tried to play the movie, I noticed the subtitles didn't work, I've stopped the movie and explicit choose the subtitle and then I showed but then I started to watch a movie after skipping some trailers (an option to choose before playing would be a great plus) and after maybe 5min playing, the video hanged and the subtitles were going on, also the audio and a couple of minutes later, the system hangs.

Hope the log file does help... It all happend around 20h on Sundag 2 november.

**Comment by NedtheNerd** [comment]
Can you check this issue with latest version 0.5.0 and advise

**Comment by glamorous** [comment]
I didn't have the time to install the new version. Hope to test it soon...

**Comment by NedtheNerd** [comment]
Remember to uncheck FFMPEG AVIO, not needed in 0.5.0.

Regards

**Comment by glamorous** [comment]
Where must this have to be unchecked?

**Comment by NedtheNerd** [comment]
Advanced Video Settings.

Regards

**Comment by NedtheNerd** [comment]
Would suggest relating card with latest version 0.5.1 and checking power supply is at least 2.0A with a good quality USB cable, trailers fully operational.  Closing issue.
