### ISSUE TITLE
Apple Bluetooth Keyboard

### ISSUE THREAD

**Issue by chrisgruggen** [RasPlex/RasPlex#315]
Running 0.4.1, trying to sync an Apple Bluetooth Keyboard through the OpenElec settings. 

Going through the prompts it connects, but can't get it to function. 

My bluetooth dongle is the Iogear Bluetooth 4.0, I checked before I ordered it is on the OpenElec approved list. 

I've been able to sync other bluetooth devices, such as the PS3 remote, but this keyboard is giving me issues. Is it possible to instal the keyboard over SSH even though OpenElec has disabled the apt-get command?

Forgive my ignorance for some of this, but I'm open to learning if I've missed something. 

Thanks
C

**Comment by dalehamel** [comment]
Is this still an issue in 0.5.1?

**Comment by chrisgruggen** [comment]
Yes, was able to get the keyboard to connect briefly after several restarts but still issues with it.

**Comment by NedtheNerd** [comment]
I have now tried several times on several versions of Rasplex and OpenELEC to pair an Apple keyboard without success. I think this issue will never be resolved with this particular keyboard.

Closing issue.
