### ISSUE TITLE
RasPlex wired Connection issue

### ISSUE THREAD

**Issue by PixelJonas** [RasPlex/RasPlex#317]
Hey Guys,

I've installed RasPlex (0.4.1) on my RaPi B Model (512MB RAM) a few weeks ago and since then I have the following problem.

It seems like the dhcp is not working. I'm connecting the Pi via LAN directly to the router (fritz.Box! 6320) but the configuration screen is telling me the Pi has an IP lke 162.xxx.xxx.xxx (I don't recall the exact numbers). I tried rebooting several times and today I installed 0.4.0rc5 to see if the problem could be resolved by trying a different version (it does not).

The fritz.Box is giving the Pi the IP 192.168.178.30 and I entered this manually via the configuration. This resolved part of the problem. My Pi can now see the server within the LAN but there is still no connection to Internet. The fritz.Box also indicates that the Pi is just using a local connection. Do you have any ideas how to solve the Problem? I really like RasPlex and everything else is working like a charm.

PS:
I tried several different OS for the Raspbery Pi (Raspbmc, Rasbian, Xbian, etc.) and never encountered a problem with the Network nor did I hat any problems with other Devices within this Network, so I guess the DHCP Server is working fine.

Unfortunatly I don't have any USB WLAN Adapter to test if this would work fine.

Thanks for your Support,
PixelJonas

**Comment by NedtheNerd** [comment]
Can you test this with the latest release 0.5.0 and advise.  No one else seems to be having this issue (over 10,000 users).

**Comment by snizzleorg** [comment]
I have the same issue. unplugging and replugging the cable a few times solves the issue

The Router is a Fritzbox

**Comment by NedtheNerd** [comment]
Not a Rasplex issue, router issue. No fix required, closing issue.
