### ISSUE TITLE
TP-Link TL-WN725N (V2) only connect @ g/b

### ISSUE THREAD

**Issue by SmoothMC** [RasPlex/RasPlex#323]
Serial number of your pi (00000000f4bbef94)
Size of Raspberry Pi (512)
Type of SD card (SDHC class 10 8Gb)
Internet connection type (Wifi)
Version of RasPlex (0.4.1)
How did you install rasplex? (gui installer, OSX)

Fresh install of Rasplex (0.4.1) two times
@ both the TL-WN725N WLAN Nano USB-Adapter only connects with 802.11g+b to FritzBox 7490 (FRITZ!OS 06.20).

Same Stick @ Win 7 works on 802.11n with 150 Mbits

where is the problem?

**Comment by NedtheNerd** [comment]
Can you check with latest release 0.5.0 and advise.

**Comment by SmoothMC** [comment]
Ok! nice 0.5. ist out!?
i will try

ps. 8188eu.ko is the driver

**Comment by dalehamel** [comment]
I believe that was one of the drivers we added

**Comment by SmoothMC** [comment]
it is still the same issue...

**Comment by NedtheNerd** [comment]
Meant to ask, how do you know it 'only connects with 802.11g+b'?

Regards

**Comment by SmoothMC** [comment]
Here it is
fresh RasPlex 0.5.0 install and get only a g/b connection

take a look ;)
![wifi fritzbox 7490](https://cloud.githubusercontent.com/assets/6202293/5769423/9bee10ee-9d1b-11e4-9600-8b6a78c4a7cd.png)

**Comment by NedtheNerd** [comment]
Have a look at this article - http://vilhelmp.blogspot.co.uk/2014/05/off-topic-tp-link-wn725n-v2-wireless-on.html

I found this after 30 seconds searching the web.

Not a Rasplex issue therefore closing the issue.

**Comment by SmoothMC** [comment]
but RasPlex depends on openelec and so the root file system is mounted as read only?
how can i change this?

regards

**Comment by dalehamel** [comment]
what chipset is it using

**Comment by NedtheNerd** [comment]
You need to run:

mount -o remount,rw /flash

Regards

**Comment by SmoothMC** [comment]
ok
i don't know how to add a driver over the volume "/flash"
the path i need is "/lib/modules/..."

a few hours ago i tried the script you posten on this image
http://snippets.khromov.se/preconfigured-airplay-speaker-shairport-downloadable-raspberry-pi-image/
an it works.

but on Rasplex (openelec) i don't have rw access to "/..."
because a fixed image is load...i think. isn't it ;)
so the driver have to compiled into the image...and here my knowledge end -.- sry

or is there another way to load the driver

**Comment by NedtheNerd** [comment]
The driver is already included in Rssplex 0.5.0.  As you obviously have no idea about what you are trying to achieve despite being given links to information, I suspect you have no Linux experience and therefore suggest that you accept that the WiFi dongle works but not at N speeds due to deficiencies in the Linux drivers for the dongle.  Buy another WiFi dongle that works.  Sorry if this sounds harsh.

**Comment by SmoothMC** [comment]
its ok
learning by doing thats my experience :p

here is my dmesg out put for the dongle

usb 1-1.2: new high-speed USB device number 4 using dwc_otg
[    3.875150] usb 1-1.2: New USB device found, idVendor=0bda, idProduct=8179
[    3.875194] usb 1-1.2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[    3.875215] usb 1-1.2: Product: 802.11n NIC
[    3.875234] usb 1-1.2: Manufacturer: Realtek
[    3.875253] usb 1-1.2: SerialNumber: 00E04C0001

i will try and try no worries ;)

**Comment by dalehamel** [comment]
please feel free to play around and report your findings - that's how open
source is done :) good luck

**Comment by SmoothMC** [comment]
hey NEW Update
I built a RasPlex with this Guide
https://github.com/RasPlex/RasPlex/wiki/Developer-launchpad

and Finally the Wireless Stick works with n connection
i change the driver from RTL8188EU-fb786d0.tar.xz to RTL8188EU-fcc9034.tar.xz

the only problem with this build is now that it is only Plex HT 1.1.3 and not 1.3.5
how can i change this? The default Branch is now: resplex-dev

Regards

**Comment by SmoothMC** [comment]
hey dalehamel...any feedback? ;)
