### ISSUE TITLE
Resume or Start from beginnig dialog

### ISSUE THREAD

**Issue by dgtlpsyche** [RasPlex/RasPlex#333]
I just installed Rasplex 0.5 and I have previously watching movies and it asks if I want to resume but if I choose start from beginning it jus goes back to the beginning. I can however choose resume and then on Plex app remote slide back to the beginning.

**Comment by dgtlpsyche** [comment]
Choosing start from beginning just goes back to the movie details screen and nothing happens. To clarify.

**Comment by scott451** [comment]
I have the same problem with PHT on a Mac Mini, so it is probably upstream. This said, I haven't found a trace of the problem elsewhere ...

**Comment by dalehamel** [comment]
upstream bug

**Comment by dgtlpsyche** [comment]
This seems to be fixed in the 5.1 version. Tried it last night.
