### ISSUE TITLE
Ensure hifiberry is fully supported (audio and video)

### ISSUE THREAD

**Issue by dalehamel** [RasPlex/RasPlex#343]
Lots of people want this, let's make sure we do in fact support it properly

**Comment by microwavesafe** [comment]
Can I ask whether this will be fixed in the next release, which I guess is 0.6.0.

**Comment by BradMeier** [comment]
No, it isn't planned for 0.6.0, hopefully the next release after that.

**Comment by microwavesafe** [comment]
Is 0.6.0 in feature freeze or is this something I can help with?

**Comment by NedtheNerd** [comment]
Yes it's frozen, hoping to get this out soon.

**Comment by microwavesafe** [comment]
I wondered if there were any further updates on this issue? Do you think there will be a fix in 0.6.1?

**Comment by NedtheNerd** [comment]
HiFiBerry is supported in next release for music playback only

**Comment by microwavesafe** [comment]
Interesting, is different software used for video and music playback? I'm guessing omxplayer is used for video so is it a limitation with this?

**Comment by microwavesafe** [comment]
Does openelec 5 use ALSA as the back end?

**Comment by NedtheNerd** [comment]
Need togged HiFiBerry (and USB DAC's) working for video playback.

**Comment by NedtheNerd** [comment]
Fixed in next release, closing issue.
