### ISSUE TITLE
Fix on deck/fanout issue

### ISSUE THREAD

**Issue by dalehamel** [RasPlex/RasPlex#345]
Sometimes fanouts don't show up, it seems to happen more often when signed into MyPlex.

Reports have said this helps fix it:

System Settings -> Network -> Advanced Network Settings -> Wait for network before starting XBMC, this seems to fix that on-deck issue.

**Comment by dalehamel** [comment]
https://github.com/RasPlex/service.openelec.settings/blob/rasplex/resources/lib/modules/connman.py#L2573

Might be fixed by new openelec settings @kwiboo

**Comment by dalehamel** [comment]
Should also be fixed in plex code: 

xbmc/network/Network.cpp
171:bool CNetwork::IsAvailable(bool wait /*= false*/)

**Comment by dalehamel** [comment]
Adding the IsAvailable call before plexapplication is started seems to resolve this

**Comment by NedtheNerd** [comment]
Appears to be fixed in next release.
