### ISSUE TITLE
PHT freeze when clicking next in "play random all"

### ISSUE THREAD

**Issue by Eloo** [RasPlex/RasPlex#356]
Hey guys,
i recently updated to RasPlex 0.5.1 and figured out an issue when playing random episodes from a TV show.
Evertime when i want to skip a episode by clicking "next" on my remote PHT is freezing. In the bottom right corner there appears a "please wait" notification but PHT seems to be dead. 

I don't know if the problem is new in the 0.5.1 version or its actually a RasPlex problem. But maybe someone other got the error too.

Infos:
Raspberry1 B Model 512MB
System is still reachable using SSH
CPU Load ~ 20% (mostly by PHT)
Killing PHT fixes the problem
PlexServer is available and reachable

If you need more information let me know

Regards Eloo

**Comment by dalehamel** [comment]
This will likely be fixed in the next release

**Comment by Eloo** [comment]
Very cool.
And i just figured out that PHT is not freezing when I'm using the on-screen option for "next" (from the small menu on bottom of the screen)

**Comment by eraserhead666** [comment]
I experience the same when selecting next episode using the on screen menu. : 
![img_1810](https://cloud.githubusercontent.com/assets/8104930/7000170/cf89bf4a-dbb7-11e4-9823-1b5b19cd7718.JPG)

**Comment by derekcentrico** [comment]
Glad to see this is reported.  I'm in the same boat with freezing.

**Comment by NedtheNerd** [comment]
Not sure what you mean by 'Play Random All', can you describe the steps to replicate this.  Thanks.

**Comment by derekcentrico** [comment]
For me, I will select the shuffle feature say for all seasons of my favorite show SouthPark.  If I try to skip to the next episode, I will likely get the freeze of "Please wait" until I power cycle the rPi2.  But if I just jump forward a few times to the end of the current playing show, Rasplex will play the next episode fine.

**Comment by NedtheNerd** [comment]
This issue is fixed in next release.

Will leave open for now, when next release is out can you check and close if appropriate.

**Comment by derekcentrico** [comment]
Ned, I can test now if you want.

**Comment by NedtheNerd** [comment]
Can you please check this issue in the latest release 0.7.0 (released today) and advise.

**Comment by derekcentrico** [comment]
I haven't experienced it yet.  Close it out and we reopen if needed?

**Comment by NedtheNerd** [comment]
Closed at request of OP.
