### ISSUE TITLE
Letters with diacritics not displaying

### ISSUE THREAD

**Issue by fxxer** [RasPlex/RasPlex#363]
I am using auto downloaded subtitles from opensubtitles by plex server (downloading Czech or Slovak subtitles). Letters with diacritics are not displayed in subtitles when I play something over RasPlex. For character set I am using Central Europe (Windows), it doesn't work with any of the 3 fonts in RasPlex. The same setup work fine with Plex client on Mac. Subtitles files are not in utf-8 (don't ask me why, but almost or subtitles are in windows format I think 1250). Is there a way how this can be fixed?

PS: If needed I can provide you the subtitles file.

**Comment by NedtheNerd** [comment]
This is not specifically a Rasplex issue, there are plenty of posts on the Plex Forums regarding this, suggest you search the whole forum for 'diacritics' and look at some of the solutions/workarounds.

Closing Issue.

Regards
