### ISSUE TITLE
NOOBS custom OS

### ISSUE THREAD

**Issue by casimir** [RasPlex/RasPlex#367]
It would be great to be able to install RasPlex from an OS package for [NOOBS](https://github.com/raspberrypi/noobs#how-to-create-a-custom-os-version). I used this to install [OpenELEC](http://www.raspberrypi.org/downloads/) and it was pretty straightforward.

**Comment by Ninmania** [comment]
I'm interested too ! 
Rasplex + Recalbox would be the perfect dualboot System :D

**Comment by NedtheNerd** [comment]
@Ninmania 

If you want dual (or multi) boot, Google for Berryboot.

**Comment by Ninmania** [comment]
Thanks you @NedtheNerd. I saw about the CEC control mode and that could fit perfectly :)

**Comment by NedtheNerd** [comment]
Closing issue, NOOBs is Berryboot!
