### ISSUE TITLE
Raspbian Support

### ISSUE THREAD

**Issue by brad999** [RasPlex/RasPlex#368]
Is there currently a working port of RasPlex for Raspbian? I've been using Rasplex for a while and love all the functionality and responsiveness. However, thanks to the increased speed of the Raspberry Pi 2, I would like to start running other services on top of Rasplex. This is currently very difficult to do with the lack of a package management system in OpenELEC.

There is a reference to a Raspbian port of the RasPlex website, but I'm not sure how recent that is.

From RasPlex website:
"RasPlex currently runs on OpenELEC for reasons of limited man power, but there is a working raspbian port that just needs some time to be brought up to speed."

**Comment by NedtheNerd** [comment]
That quote is from a few years ago.  With the recent price drop on the B+ why not buy another as its unlikely that Rasplex will ever run on Raspbian.  You could also try BerryBoot, which allow multiple booting.  Guide to doing this is in the forums.
