### ISSUE TITLE
Occasional Black 'flicker' whilst streaming

### ISSUE THREAD

**Issue by dankellys** [RasPlex/RasPlex#380]
Serial number: Rasp Pi 2 Model B 1GB (Serial unknown)

Rasplex version: Latest from http://www.rasplex.com/get-started/rasplex-installers.html using Windows Gui installer

Plex media server version: 0.9.12.1.1079-b655370

Description of the bug: During playback, occasionally, the screen goes completely black, audio and video stops for around 1 second, then playback resumes. Once playback resumes, my TV indicates I am using HDMI3 (which is the connection used by the Pi).  However, it normally only displays this if you connect to a new source, or a device connected to that source boots up.  So it suggests the Pi is not sending signal via HDMI for that split second, then when it starts again, the TV recognises a device.

Extract from Plexhometheatre.log:

WARNING: CPlexHTTPRemoteHandler::updateCommandID no commandID sent to this request!
15:03:36 T:1975373824  
NOTICE: COMXPlayer::CloseFile
15:03:36 T:1975373824  
NOTICE: COMXPlayer: waiting for threads to exit
15:03:36 T:1457517648  
NOTICE: COMXPlayer::OnExit()
15:03:36 T:1457517648  
NOTICE: OMXPlayer: closing audio stream
15:03:36 T:1457517648  
NOTICE: Closing audio stream
15:03:36 T:1488974928  
NOTICE: thread end: OMXPlayerAudio::OnExit()
15:03:36 T:1457517648  
NOTICE: OMXPlayer: closing video stream
15:03:36 T:1457517648  
NOTICE: Closing video stream
15:03:36 T:1465906256  
NOTICE: thread end: video_thread
15:03:36 T:1457517648  
NOTICE: OMXPlayer: closing subtitle stream
15:03:36 T:1457517648  
NOTICE: Closing subtitle stream
15:03:36 T:1457517648  
NOTICE: COMXPlayer::OnExit() deleting demuxer
15:03:36 T:1457517648  
NOTICE: COMXPlayer::OnExit() deleting input stream
15:03:36 T:1975373824  
NOTICE: COMXPlayer: finished waiting
15:03:36 T:1975373824  
NOTICE: COMXPlayer::CloseFile
15:03:36 T:1975373824 
WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
15:03:36 T:1975373824  
NOTICE: COMXPlayer: waiting for threads to exit
15:03:36 T:1975373824  
NOTICE: COMXPlayer: finished waiting
15:03:36 T:1975373824  
NOTICE: Enumerated Pi devices:
15:03:36 T:1975373824  
NOTICE:     Device 1
15:03:36 T:1975373824  
NOTICE:         m_deviceName      : HDMI
15:03:36 T:1975373824  
NOTICE:         m_displayName     : HDMI
15:03:36 T:1975373824  
NOTICE:         m_displayNameExtra:
15:03:36 T:1975373824  
NOTICE:         m_deviceType      : AE_DEVTYPE_HDMI
15:03:36 T:1975373824  
NOTICE:         m_channels        : FL,FR
15:03:36 T:1975373824  
NOTICE:         m_sampleRates     : 8000,11025,16000,22050,24000,32000,44100,48000,88200,96000,176400,192000
15:03:36 T:1975373824  
NOTICE:         m_dataFormats     : AE_FMT_FLOAT,AE_FMT_S32LE,AE_FMT_S16LE,AE_FMT_AC3,AE_FMT_DTS,AE_FMT_EAC3
15:03:36 T:1975373824  
NOTICE:     Device 2
15:03:36 T:1975373824  
NOTICE:         m_deviceName      : Analogue
15:03:36 T:1975373824  
NOTICE:         m_displayName     : Analogue
15:03:36 T:1975373824  
NOTICE:         m_displayNameExtra:
15:03:36 T:1975373824  
NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
15:03:36 T:1975373824  
NOTICE:         m_channels        : FL,FR
15:03:36 T:1975373824  
NOTICE:         m_sampleRates     : 48000
15:03:36 T:1975373824  
NOTICE:         m_dataFormats     : AE_FMT_FLOAT,AE_FMT_S32LE,AE_FMT_S16LE
15:03:47 T:1457517648  
NOTICE: Thread XBPyThread start, auto delete: false
15:03:48 T:1457517648  
NOTICE: -->Python Interpreter Initialized<--
15:03:49 T:1975373824   
ERROR: Control 1000 in window 13000 has been asked to focus, but it can't
15:06:14 T:1457517648  
NOTICE: Thread RemoteSubscriber: 7E4EC5C9-2143-4FBE-A000-807205A744E6 start, auto delete: false

**Comment by NedtheNerd** [comment]
Have you tried changing the HDMI cable?  Cheap or old cables can cause this issue.

**Comment by NedtheNerd** [comment]
Can you please check this issue in the latest release 0.7.0 (released today) and advise.

**Comment by NedtheNerd** [comment]
No further response from OP, closing issue.
