### ISSUE TITLE
Plug and Play Keyboard Support

### ISSUE THREAD

**Issue by didyouexpectthat** [RasPlex/RasPlex#384]
Rasplex doesn't seem to be able to understand when I plug in a keyboard after it has already booted. It has persisted since I started with 0.4. It works fine when you start RasPlex with a USB put in already. This appears to only be a problem with the keyboard. I have also used my Raspberry Pi to charge a phone and it at least acknowledges USB capabilities.  This has persisted different Raspberry Pi devices so specifics don't seem necessary.

**Comment by NedtheNerd** [comment]
Known issue, plug and play has never worked for keyboards in any version of Rasplex. Probably never will.  Leave your keyboard plugged in.

We are aware of the issue, will close this.
