### ISSUE TITLE
Add Raspberry Pi2 support?

### ISSUE THREAD

**Issue by chownsauce** [RasPlex/RasPlex#387]
What all would be involved in adding pi2 support to this release? Is it as simple as using the kernel from 0.5.1? This to me has been the stablest release.

**Comment by dalehamel** [comment]
@chownsauce 0.6.0 already supports the raspberry pi 2.

**Comment by chownsauce** [comment]
Yea but they dropped VPN support in the later version of OpenELEC.

**Comment by dalehamel** [comment]
there's a substantial amount of work involved in making a release work on Pi2 - it's a different kernel and completely different ABI. We have another ticket discussion the possibility of adding openvpn support back for a future release.

**Comment by chownsauce** [comment]
Gotcha, thanks for all your hard work!
