### ISSUE TITLE
How to interface properly with hyperion on Rasplex 0.6.0?

### ISSUE THREAD

**Issue by tlnagy** [RasPlex/RasPlex#388]
I did a clean reinstall when switching to Rasplex 0.6.0 and I'm not sure how to get my lights working again. I have hyperion enabled in the gui and I checked that I have dtparam=spi=on in config.txt. Also I can't replace /etc/hyperion.config.json because it is marked readonly, how can I work around that?

**Comment by dalehamel** [comment]
Place your config in /storage/.config, as hyperion.config.json. This overrides the system default.

**Comment by tlnagy** [comment]
Thank you. I figured out the problem, I had accidentally flipped the GPIO connection and the RPi wasn't able to communicate with the lights.
