### ISSUE TITLE
Not saving video settings

### ISSUE THREAD

**Issue by taenzerme** [RasPlex/RasPlex#389]
Video settings made during playback (interlacing, crop black bars etc.) are not saved as defaults and have to be redone everytime. PlexHT on MacOS did actually have this some time ago but does not save at the moment, too. Would be nice to have this, though.

**Comment by NedtheNerd** [comment]
Can you please check this issue in the latest release 0.7.0 (released today) and advise.

**Comment by NedtheNerd** [comment]
When, and if, Plex HT fix the issue then this will filter down into Rasplex.

Closing issue.
