### ISSUE TITLE
0.7.0 can't change Language.

### ISSUE THREAD

**Issue by brutevinch** [RasPlex/RasPlex#395]
After i choose Russian, my RPi b+ stuck. Waiting 5-10min no matter. 
0.5.0 all works fine.

**Comment by NedtheNerd** [comment]
Just tried this, works OK, although it does take a little time to apply the changes, image attached.

![image](https://cloud.githubusercontent.com/assets/7222247/8883999/01c719fa-324b-11e5-8973-f5d7bc8c963e.jpg)

**Comment by NedtheNerd** [comment]
Closing issue.

**Comment by brutevinch** [comment]
Which skin do you use? Can you share it?

**Comment by NedtheNerd** [comment]
Skin is DeadEyeFlint's Plex Black Edition, see here https://forums.plex.tv/discussion/129756/release-plex-black-edition/p1

Regards

**Comment by brutevinch** [comment]
Thank you!
