### ISSUE TITLE
Remote control numbers not working for Plex Home User login

### ISSUE THREAD

**Issue by Reilos** [RasPlex/RasPlex#397]
Using CEC. The numbers on the TV's remote control cannot be used anymore to type the login code for a Plex Home user. Only on the screen a numpad is shown, for which you can use the remote control arrow and OK keys to enter the code. This is of course totally undesired, as now anyone can see the code you are entering on the screen. RPI2 and a Samsung UE48HU7500.

**Comment by yannlet** [comment]
Same probleme for me with a samsung PS63C7700 and RPi2.

**Comment by Reilos** [comment]
same problem on my other samsung tv

**Comment by Kwiboo** [comment]
Please try with RasPlex 0.7.1, it contains updated input handling and keymapping.

**Comment by Reilos** [comment]
Nope, still the same problem. The (new) user selection screen does not take the numbers on the remote for login credentials.

**Comment by LegeDoos** [comment]
+1

**Comment by NedtheNerd** [comment]
Can you check in latest release and advise if fixed.

**Comment by Reilos** [comment]
It's working fine now on my Samsung UE48HU7500. Thanks!

**Comment by NedtheNerd** [comment]
Closing issue.
