### ISSUE TITLE
Hang on fwd (end of movie)

### ISSUE THREAD

**Issue by glamorous** [RasPlex/RasPlex#398]
I've just installed the latest version 0.7.0 on my Raspberry Pi 2 and when I fwd x8 near to the end of the file, suddenly it stopped and hanged... I suppose because it was at the end of the file but couldn't forward any further and "crashed". I ssh'd to it to reboot the pi and it works again...

**Comment by NedtheNerd** [comment]
I have tried this on a number of movies and TV shows, when FF reaches end of video playback, playback terminates and returns to post-play screen, issue cannot be replicated, closing issue.
