### ISSUE TITLE
0.7.0 CEC stuck.

### ISSUE THREAD

**Issue by brutevinch** [RasPlex/RasPlex#400]
lg mt 55 v. After few hours cec stucks. When i start masturbate my remote control, for ex. up down center up down it MAYBE wakes up. Very unstable build such 0.6.0 such 0.5.1. Only 0.5.0 works well without any issues.

**Comment by BradMeier** [comment]
Which Pi do you have? RPi1B, RPi1B+ or RPi2B?

**Comment by NedtheNerd** [comment]
Closing this as there is no detail, just entering a title is not helpful. Read the instructions for filing an issue please.

**Comment by brutevinch** [comment]
@BradMeier RPi B+ , clean install 0.7.0 , default configuration cec in rasplex.
