### ISSUE TITLE
RasPlex has no audio when playing AAC 5.1 audio tracks

### ISSUE THREAD

**Issue by MarshallOfSound** [RasPlex/RasPlex#402]
When I select 5.1 as my desired audio output and then play a movie with AAC 5.1 audio nothing plays through the speakers.  Can we force AAC 5.1 to be transcoded to AC3 5.1 at the server side?

**Comment by NedtheNerd** [comment]
AAC5.1 audio plays fine through a suitable receiver - display on receiver shows LPCM 3/2.1.

Check that you have enabled passthrough for all options for capable receiver.

Selecting 5.1 when connected only to a TV is incorrect.

**Comment by MarshallOfSound** [comment]
All options are configured correctly (I believe)

An interesting behaviour is when I choose a combination of "Force Transcoding" and "Quality = 20Mbs" it plays 5.1 correctly.  With those two options set to "off" and "Direct Play" respectively it does not
