### ISSUE TITLE
Bluetooth keyboard doesn't work

### ISSUE THREAD

**Issue by andoriyu** [RasPlex/RasPlex#405]
Keyboard displayed as connected. Keyboard itself indicates that it's connected, but no input whatsoever. Smashing buttons on keyboard make BT dongle to flash its LED, but nothing happens. I know that this keyboard adapter works because both were used on raspbian few hours ago with no issues.  

First generation of pi (well, 1.5 gen). 0.7.0 version of rasplex

**Comment by NedtheNerd** [comment]
Known issue, no Bluetooth devices work, USB wireless keyboards work fine, plenty of recommendation in the forums.

Regards

**Comment by Velociraptor85** [comment]
https://github.com/RasPlex/RasPlex/issues/358

**Comment by NedtheNerd** [comment]
Fixed in next release.

**Comment by Velociraptor85** [comment]
+1 Works :)
