### ISSUE TITLE
Installer does not download image on Mac

### ISSUE THREAD

**Issue by adrianmihalko** [RasPlex/RasPlex#406]
Hi,

I tried to download .img using the automatic installer on Mac Os X, but it does not worked. Here is the log file:

http://pastebin.com/HtK4yH2B

**Comment by NedtheNerd** [comment]
Did you follow the instructions here https://github.com/RasPlex/RasPlex/wiki/GetRasPlex-Mac-OSX-GUI

Works fine for me for either RPi or RPi2.

**Comment by NedtheNerd** [comment]
If used according to instructions it works.  Closing issue
