### ISSUE TITLE
 Plug and Play Keyboard Support, Part 2

### ISSUE THREAD

**Issue by m00dawg** [RasPlex/RasPlex#416]
I noticed in issue 384 you mentioned plug and play keyboard support will never work? Curious as to why? OSMC doesn't have issues with that? Or, more to the point, I can use a KVM to switch to/from my rPi and my desktop machines via OSMC. I cannot do this in RasPlex which makes it very difficult to use with my specific setup.

**Comment by Kwiboo** [comment]
This should be fixed in next release.

**Comment by m00dawg** [comment]
:rocket:

**Comment by NedtheNerd** [comment]
@m00dawg 

Can you check in latest release 0.7.1 and advise.

**Comment by m00dawg** [comment]
Works like a champ!

There is a delay when switching to the rPi before the keyboard works (about 5 seconds), which isn't a big deal. Other than that, it seems to work without issue!

Thanks!

**Comment by NedtheNerd** [comment]
Delay is normal. Closing issue.
