### ISSUE TITLE
CEC connects but doesn't work on Samsung 6300

### ISSUE THREAD

**Issue by rbeall** [RasPlex/RasPlex#417]
Running reasplex 0.6.0.  Works fine on two other samsung tv's but gave it to my buddy and he can't control CEC through his remote.  It is showing up as "updated" and "connected" to the TV.  The Anynet+ is showing "Plex" so they are in communication however the stock tv remote isn't controlling the pi?  Thoughts?

**Comment by NedtheNerd** [comment]
Can you check on latest release - 1.0.0 - and advise.

**Comment by NedtheNerd** [comment]
No further feedback, closing issue.
