### ISSUE TITLE
0.7.0 Fresh Install DNS Troubles.

### ISSUE THREAD

**Issue by mewersthecat** [RasPlex/RasPlex#422]
When I do a fresh 0.7.0 Install using wired internet the DNS doesn't work at all.. I made sure the DNS servers in the interface... To get it to work i have to SSH in, and edit /etc/resolv.conf 
but every time i reboot the device, I have to do it again.. can't uninstall resolvconf no idea how to even fix it..

**Comment by Risca** [comment]
What does your resolv.conf look like before you edit it?

**Comment by NedtheNerd** [comment]
Can you use latest version 0.7.1 and advise.

**Comment by NedtheNerd** [comment]
No further feedback, assuming everything OK, closing.
