### ISSUE TITLE
Managed users can't reboot/shutdown RasPlex 0.7.1

### ISSUE THREAD

**Issue by bbaraniec** [RasPlex/RasPlex#434]
I have updated my Rasberry Pi 2 B to 0.7.1. When you press left arrow on main menu you have options like reboot, shutdown and switch user. Only admin of Home Plex has option to reboot and shutdown, all managed users have switch user only. Is this intended? PHT on Windows works for them.
As requested by NedtheNerd https://forums.plex.tv/discussion/comment/1049348/#Comment_1049348

**Comment by Kwiboo** [comment]
In PHT on Windows/OSX Quit and Sleep is available for managed users and Shut Down is restricted to admins only. On RasPlex the Quit and Sleep function is removed since there are no equivalent functionality supported but a Restart option has been added for admins only.
Next release will have a skin option to enable Shut Down and Restart for managed users.

**Comment by bbaraniec** [comment]
Great. Thanks for that.

**Comment by NedtheNerd** [comment]
Fixed in next release - 1.0.2.

**Comment by bmlevine11** [comment]
Hey

On Monday, January 18, 2016, NedtheNerd <notifications@github.com> wrote:

> Fixed in next release - 1.0.2.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RasPlex/RasPlex/issues/434#issuecomment-172761393>.
>


-- 
Brian Levine
bmlevine11@gmail.com
(630)-806-9344

**Comment by bmlevine11** [comment]
Join me

On Monday, January 18, 2016, Brian Levine <bmlevine11@gmail.com> wrote:

> Hey
>
> On Monday, January 18, 2016, NedtheNerd <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> Fixed in next release - 1.0.2.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/RasPlex/RasPlex/issues/434#issuecomment-172761393>.
>>
>
>
> --
> Brian Levine
> bmlevine11@gmail.com
> <javascript:_e(%7B%7D,'cvml','bmlevine11@gmail.com');>
> (630)-806-9344
>
>

-- 
Brian Levine
bmlevine11@gmail.com
(630)-806-9344
