### ISSUE TITLE
Cannot save IPv4 Settings

### ISSUE THREAD

**Issue by pkinnane** [RasPlex/RasPlex#438]
Rasplex 1.0.0 installed via img on Rasp Pi 2b.
Set a manual (static) IP address, and the Cancel/Save buttons cannot be navigated to to save the settings.

**Comment by pkinnane** [comment]
Mmmmm, went out and back in to the IPv4 settings and COULD access the Save button - so something amiss,but not able to reproduce at the moment.

**Comment by NedtheNerd** [comment]
Works as expected, closing issue.
