### ISSUE TITLE
Web UI

### ISSUE THREAD

**Issue by jilani2423** [RasPlex/RasPlex#444]
Hi,

I have installed RasPlex on Raspberry Pi ver 1 and then when I enabled web and http related setting to access using the 32400 port. I am not able to access that in other system browser. Please let me know If I am missing anything or it is a bug.

from SSH
RasPlex:~ # ps aux | grep plex
  404 root       4:06 /usr/lib/plexht/plexhometheater --standalone -fs --lircdev /run/lirc/lircd

is it due to standalone when it started?

I am using the latest from here on 11-30-2015
http://www.rasplex.com/get-started/rasplex-installers.html

I have one more concern here, when I tried to mount 500 GB disk, I am not able to mount this, The reason I found is file system which is NTFS for my disk, I have tested with one more disk with NTFS not working then I formatted with exFAT, then I am able mount.and access. I am assuming some ntfs support libraries are not added.

Thanks,
Jilani

**Comment by Kwiboo** [comment]
Rasplex is only a client, closing.
