### ISSUE TITLE
shared channels in rasplex

### ISSUE THREAD

**Issue by firsttris** [RasPlex/RasPlex#445]
Hello,

on a shared library i doesn't see "channels". i only see movies und tvshow.
i see channels on the web and on the app but not on rasplex.
tested 1.0.0 and 1.0.1.
(and yes i have allowed shared channels for this user)

have i missed something?

when im logged-in as owner i see channels why not on a shared library?

regards
firsttris

**Comment by NedtheNerd** [comment]
Shared Libraries are just that, Channels are not Libraries. There is no option in PMS to share Channels when sharing Libraries.

**Comment by firsttris** [comment]
Sure.. You can share channels on PMS.... 
You just need to active this option:
https://support.plex.tv/hc/en-us/articles/201812473-Why-don-t-Channels-appear-for-shared-users-

**Comment by firsttris** [comment]
found out its working if i add a user to plex home. before i added as friend.

**Comment by Kwiboo** [comment]
Rasplex currently do not load channels for shared servers. Shared channels is a relative new feature of PMS and next Rasplex release will most probably have support for shared channels.

**Comment by firsttris** [comment]
thx for your answer i will close this issue.
