### ISSUE TITLE
unable to play from usb audio

### ISSUE THREAD

**Issue by firsttris** [RasPlex/RasPlex#446]
hello, my usb-dac (nubert no-pro) is not working with rasplex 1.0.1.

i have the same settings like in openelec. (working in openelec)

audio device: ALSA USB AUDIO DAC, SPDIF
passthrough: ALSA USB AUDIO DAC, S/PDIF

no matter witch setting i choose it plays from hdmi.

regards
tristan

**Comment by NedtheNerd** [comment]
USB DAC support is only for Music tracks only at the moment, not for movies or TV shows.  See topics in forum. Closing issue.

**Comment by OChrisJonesO** [comment]
Why would this be music only? what difference does it actually make whether the audio track is from a movie/tv show or a song?

**Comment by NedtheNerd** [comment]
Music and Video use different players, hoping to get this addressed in 1.6 release.

**Comment by OChrisJonesO** [comment]
Any timeline for that to be supported? or is there any workaround possible right now?

Currently stuck using the crappy speakers in my projector over HDMI for audio on tv shows / movies. Music plays fine over my 5.1 speakers however, (tested and forced stereo output to 5.1, all speakers are active). A bit annoying.

Currently setup using a USB soundcard with Logitech z506 speakers. Under RasPlex preferences, audio output device shows up just fine (ALSA:USB Sound Device (@:CARD=Device,DEV=0), Analog).

**Comment by NedtheNerd** [comment]
No timeline and no workarounds at the moment, sorry.

**Comment by Ribwich12** [comment]
I'm just running into this issue myself. Has there been any progress?

**Comment by NedtheNerd** [comment]
Yes, as previously stated, next release.

**Comment by Ribwich12** [comment]
Ok thanks. I'm new to Rasplex so I'm not familiar with what release was next.
