### ISSUE TITLE
Subtitles missing special characters if not UTF8

### ISSUE THREAD

**Issue by iBobik** [RasPlex/RasPlex#448]
When I play movie with SRT subtitles encoded in cp1250 (common for Czech subtitles) special diacritics characters are missing in the subtitles (e.g. "přísloví" is shown like "pslov"). If I encode the same SRT file with UTF8 encoding, the same characters are printed to screen correctly.

**Comment by NedtheNerd** [comment]
Not an issue, all Plex clients require subs to be UTF8 encoded to obtain the correct character set, re-rip your BD/DVD with this option.

Closing issue

**Comment by iBobik** [comment]
Just for record: This should solve it:
https://github.com/ukdtom/SRT2UTF-8.bundle



Jan Pobořil

2015-12-11 18:26 GMT+01:00 NedtheNerd <notifications@github.com>:
