### ISSUE TITLE
RasPlex v1.0.1 crash on TV episode via Plex Mobile remote.

### ISSUE THREAD

**Issue by Tommo2008** [RasPlex/RasPlex#451]
Hello,

Current system Config:

Raspberry Pi2, RasPlex v0.7.1/1.0.1
Iphone 5, Plex App v4.0.9 / HTC One M8, Plex App 4.17.2.488.

Whilst playing a TV episode and attemping to switch to another episode using the above phone apps my Pi2 appears to crash.

This issue is repeatable on my devices by selecting the episode via the phone app and is not limited to particular episodes.

Ive turned on debug logging and checked the resulting logs but they do not appear to show anything useful but have attached the logs below:

[Plex Media Server Log.txt](https://github.com/RasPlex/RasPlex/files/67607/Plex.Media.Server.Log.txt)

.16 is my Pi2.

Any help would be greatly appreciated.

**Comment by NedtheNerd** [comment]
Tried to replicate in 1.0.3 (using PMS 0.9.16.0)

Start episode playing from iPhone, after a couple of minutes select another episode and press play, first episode stops playing, second episode starts playing - no crashes.

Closing issue.
