### ISSUE TITLE
RasPlex 1.0.1 - Crash while playing music and SSH into the RPi2

### ISSUE THREAD

**Issue by trumpy81** [RasPlex/RasPlex#454]
Serial Number = Where do I find that?
Crash ID = 3088
Size of Pi = Raspberry Pi 2 Model B
SD card = SanDisk Ultra Class 10 8GB
Connection = WiFi
RasPlex = 1.0.1
Logs = below
Installed = Get-RasPlex 1.0.1
Description = I was playing a music track from my PC PMS install and I SSH'ed into the RPi2 with PuTTY in order to download the RemotePi configuration tool. The tool downloaded, I chmod'ed the file and then ran ./mslconfigtool -l to check the settings, the settings displayed correctly in PuTTY and then RasPlex crashed.

It returned to the RasPlex screen not the OpenELEC screen and rebooted into RasPlex. The crash report dialogue then displayed with the crash ID of 3088.

This is a fresh install Of RasPlex on a brand new card.

If there is anymore information needed, just let me know. Thanks.

[plexhometheater.log.txt](https://github.com/RasPlex/RasPlex/files/73269/plexhometheater.log.txt)

[plexhometheater.old.log.txt](https://github.com/RasPlex/RasPlex/files/73270/plexhometheater.old.log.txt)

**Comment by NedtheNerd** [comment]
@trumpy81 

Is this still happening on 1.0.3?

**Comment by trumpy81** [comment]
I haven't upgraded to 1.0.3 yet and the rasplex.com site is down, not reachable for some reason.

1.0.2 has been working flawlessly for me no issues apart from a single crashes while navigating through my TV Show library, which I suspect was network related.

When I am able to install 1.0.3 I will test it and see if I get the same issue or not.

**Comment by trumpy81** [comment]
I upgraded to 1.0.3, finally, and no sign of this issue at all so far. Everything is working well.

This can be closed. :)

**Comment by NedtheNerd** [comment]
Closing issue.
