### ISSUE TITLE
[Feature Request] Change TV Recently Added to season instead of episode

### ISSUE THREAD

**Issue by benjaminwolf** [RasPlex/RasPlex#457]
Is it possible to change the Recently Added section to display a single season or show icon for recently added media? When you add a whole season/series to PMS, it pushes all other recently added media off of the section.

**Comment by edjonesy** [comment]
This would be an excellent improvement.

**Comment by sguilly123** [comment]
I also would like to see this implemented.

**Comment by Electronickss** [comment]
Have there been any improvements on this?

**Comment by bkury** [comment]
done ...

https://github.com/bkury/OpenPHT/commit/7aadfd804599e35b4625f0dc637d7c34333415f5
https://github.com/bkury/OpenPHT/commit/89d3a32571568d98f451d6cb9e8a180b9ff96107

**Comment by j3g** [comment]
excellent news!
what build can we find the fix?

**Comment by bkury** [comment]
There are no official/stable builds yet but this feature will be in OpenPHT v1.7.0

If you don't mind testing a pre-release, you could also take a look here :
https://github.com/bkury/OpenPHT/releases
