### ISSUE TITLE
[Feature Request] Audio via Bluetooth

### ISSUE THREAD

**Issue by mrmorton** [RasPlex/RasPlex#459]
I would really find this feature very useful. Especially with the amount of new bluetooth speaker, soundbars and headphones showing up, I could imagine a lot of other people will find this useful too.

I just bought and Apple TV 4 - only because it supports sound over bluetooth AND Plex :-)

Otherwise great job !!! Hopefully you will add sound over bluetooth to the list ;-)

Kind Regards
Morten

**Comment by NedtheNerd** [comment]
Included in latest 1.6.0 release, closing issue.
