### ISSUE TITLE
Download links not working

### ISSUE THREAD

**Issue by petrklus** [RasPlex/RasPlex#469]
Trying to get RasPlex but only getting 404 pages:

http://www.rasplex.com/get-started/download-rasplex.html
http://www.rasplex.com/get-started/rasplex-installers.html

**Comment by NedtheNerd** [comment]
You can get both Rasplex and the release from GitHub, see Release and Wiki.  We are aware of the issue.

**Comment by petrklus** [comment]
Thank you!

**Comment by dalehamel** [comment]
Just getting back from vacation, not sure what could have caused the issue.
Thanks for bring this up we will have this fixed shortly.
