### ISSUE TITLE
[Feature Request] Change FF/RW to timeline scrub using BIF files.

### ISSUE THREAD

**Issue by benjaminwolf** [RasPlex/RasPlex#471]
This issue was brought up a problem with skipping through or FF/RW transcoded streams from a remote server.

https://forums.plex.tv/discussion/202155/awfully-slow-ff-rw-during-transcoding#latest

A solution to the problem would be to use a timeline scrub method of finding your place in the media file used by some other Plex clients such as the Roku Client.

https://support.plex.tv/hc/en-us/articles/202197528-Video-Preview-Thumbnails

This method avoids the pitfalls of the current skip and FF/RW options by pausing the media stream during the scrubbing and restarting the stream from a specific time within the media file instead of having to start and stop the transcode over and over while looking for the desired scene.

**Comment by NedtheNerd** [comment]
When investigating this note that not everyone generates BIF files due to storage impact.

**Comment by cyrosystems** [comment]
+1 for this feature please, both local and remote playback fast forward and rewind on a timeline.

**Comment by Kwiboo** [comment]
Parts of this feature request is included in the 1.6.0 release.

There is now support for adaptive seeking and once adaptive seeking is performed a small preview thumbnail will be shown if PMS has generated video preview thumbnails.

**Comment by Kwiboo** [comment]
I consider this feature request implemented with the final piece being configurable seek steps.
