### ISSUE TITLE
Transcode DTS to AC3

### ISSUE THREAD

**Issue by ZyberSE** [RasPlex/RasPlex#474]
RasPlex 1.0.3 on a RPi2 can't re-encode DTS to AC3 and send it over HDMI. It sounds like it just takes the rear channels and output them as a simple stereo stream.

My SONOS system confirms that the signal is a normal stereo stream when playing DTS, but when playing AC3 it's Dolby Digital 5.1 as expected.

**Comment by NedtheNerd** [comment]
Can you try latest 1.6.0 release and advise.

**Comment by ZyberSE** [comment]
I just re-installed 1.6 and I still do not get DTS -> AC3 transcoding to work.
Is there any particular settings I need to adjust?

**Comment by ZyberSE** [comment]
Just tried the same thing on a new RPi 3 with the exact same result :(

**Comment by Kwiboo** [comment]
You need to activate "Enable Dolby Digital transcoding" in the audio output preferences.
See http://kodi.wiki/view/Audio_settings for an overview of all options, OpenPHT uses similar options.

**Comment by ZyberSE** [comment]
I can't find that option in the GUI?

**Comment by NedtheNerd** [comment]
Near the bottom of Preferences-System-Audio output.

**Comment by ZyberSE** [comment]
I have...
Enable passthough
Passtrough output device
-- DD (AC3) cap.. rec..
-- DD Plus
-- DTS

**Comment by NedtheNerd** [comment]
Set speakers to 2.0, enable Passthrough, check Dolby Digital (AC3) capable receiver, check Enable Dolby Digital transcoding.

**Comment by ZyberSE** [comment]
Wohoo, it's working! :)
(but I would never had figured it out without your instructions, the gui could be more self-explanatory)

**Comment by NedtheNerd** [comment]
Closing issue

**Comment by NedtheNerd** [comment]
@ZyberSE 

I have updated my Rasplex Audio Guide on the forums.
