### ISSUE TITLE
RasPlex 1.0.3 - Small error in Search Results

### ISSUE THREAD

**Issue by trumpy81** [RasPlex/RasPlex#477]
When doing a search, the results are displayed, but there is a small text justification error above the results.

Not a huge issue, but it should be corrected IMHO.

Also, you'll notice the duplicate results as well.

See the top center of the following image:

![wp_20160331_002](https://cloud.githubusercontent.com/assets/12381786/14154807/d76c1fbc-f701-11e5-8af1-7a397b23d8e0.jpg)

**Comment by NedtheNerd** [comment]
Can you confirm fixed in 1.6.0 just released, thanks.

**Comment by trumpy81** [comment]
I can confirm it is fixed in 1.6.0 :)

Thanks!! :dancer:

**Comment by NedtheNerd** [comment]
Closing issue.
