### ISSUE TITLE
Build libass with HarfBuzz enabled

### ISSUE THREAD

**Issue by SafaAlfulaij** [RasPlex/RasPlex#482]
Arabic shaping break if HarfBuzz isn't used (issues differs from a font to font).
Issue describing the problem (images included): https://github.com/libass/libass/issues/134 (The problem is with Aegisub for Windows as well)
An issue for SuperTuxKart regarding supporting Fribidi (Done in Rasplex) and Harfbuzz: https://github.com/supertuxkart/stk-code/issues/2320

Example of using Fribidi without HarfBuzz:
![Image of text without HarfBuzz shaping](https://cloud.githubusercontent.com/assets/3252341/10266151/b523337a-6a82-11e5-8cc1-7b9ddfc5b247.png)
Same example but the HarfBuzz used (Notice the diacritics and some other characters (check: https://en.wikipedia.org/wiki/Arabic_alphabet#Ligatures):
![Image of text with HarfBuzz shaping](https://cloud.githubusercontent.com/assets/3252341/10658408/27cc3292-78c9-11e5-833c-df2892ccfb16.png)

Please let me know if you want a detailed description

**Comment by SafaAlfulaij** [comment]
I see the label "Done" there, is it done and you are testing it or what? :)
Can you grab me the patch or the RaspberryPi's ISO to check?

**Comment by NedtheNerd** [comment]
You will have to wait for the Pre-release version.

**Comment by SafaAlfulaij** [comment]
I just like to add something, when the subtitle (SSA) is embedded into the MKV file (in my case), the text renders correctly and without any problems, but when it's side by side to the video it does not.

**Comment by NedtheNerd** [comment]
Can you try with latest 1..6.0 release and advise.

**Comment by SafaAlfulaij** [comment]
Unfortunately, still not rendering the text correctly  :(
Can you lead me to the changes you made? I may have an idea...
Thanks for your work!

**Comment by NedtheNerd** [comment]
Release 1.6.1 is out, can you check, hopefully this issue is nice fixed for you.

**Comment by SafaAlfulaij** [comment]
Yeah! That fixed it! Huge thanks!
