### ISSUE TITLE
Raspberry Pi 3 - Error Message at startup...

### ISSUE THREAD

**Issue by Massaguana** [RasPlex/RasPlex#496]
Hello RasPlex Team,

with my new Raspberry Pi 3 and Rasplex 1.0.3 there are an Error Message at every Startup...

[   0.267214 ] brcmvirt-gpio soc:virtgpio: Failed to map physical address

What should say this?

Regards
Massaguana

**Comment by NedtheNerd** [comment]
You can ignore this.

Closing issue.
