### ISSUE TITLE
Raspberry Pi 3 & RemotePi Board - Remote don´t woking

### ISSUE THREAD

**Issue by Massaguana** [RasPlex/RasPlex#497]
Hello RasPlex Team,

wood like to use my Raspberry Pi 3 with an RemotePi Board an my Apple Remote "A1294"...

here are the lirc config for it: http://lirc.sourceforge.net/remotes/apple/A1294

The Power ON OFF with Apple Remote and RemotePi Board are working fine... but the navigation with my remote an RasPlex don´t work.

I habe create an custom "lircd.conf" file and activate RemotePi Support and disable CEC. But it is not possible to navigate in RasPlex no reaction.
I test with an "Standart" DreamMultimedia remote that stored in "lircd.config.rpi". same Problem...

What can i do to make it work? Is it possible to show the lirc information? what he receives etc.

Regards
Massaguana

**Comment by NedtheNerd** [comment]
Enable debug and tail the log and then press each button on the remote, each button press will be shown in the log if recognised.

Closing this issue as it is not an issue and you have posted a topic on the forum asking for help.
