### ISSUE TITLE
Missing protocol Bluetooth 

### ISSUE THREAD

**Issue by gameslayer** [RasPlex/RasPlex#498]
When trying to connect my bluetooth Sony headphones  I get a error saying missing protocol

**Comment by NedtheNerd** [comment]
Bluetooth audio is not currently supported, will be in next release, closing issue.

**Comment by gameslayer** [comment]
Do you know when the next release is coming out? I would love to be able to connect bluetooth headphones as a option?

**Comment by NedtheNerd** [comment]
Hopefully next week

**Comment by gameslayer** [comment]
Awesome can't wait
