### ISSUE TITLE
Crash when change Screen fps

### ISSUE THREAD

**Issue by Massaguana** [RasPlex/RasPlex#500]
Here are an issue that occures with Rasplex 1.0.3 and also with new OpenPHT 1.6.0 for an RaspberryPi 3 with RemotePi Board.

When i Change the screen fps from 60 to 50 the system Crash´s...

Crash Report: 0607-1413
![img_1955](https://cloud.githubusercontent.com/assets/15521791/15860951/582f7d48-2ccb-11e6-9463-4e8a857543c6.JPG)

i think the [u] and [/u] are also wrong...

**Comment by Massaguana** [comment]
some times RasPlex son´t save the fps Setting 50Hz. It Start Up with 60 HZ. Change is only to 59,94Hz possible, after an Restart is 50Hz back...

**Comment by NedtheNerd** [comment]
I have tried to replicate your crash without success, changing refresh rate sticks on restart, closing issue.

**Comment by Massaguana** [comment]
Sorry Ned, but why there are an CrashReport? There are no Informations in it?

Here no problem to replictae this issue. not at all time but 25% Crash
