### ISSUE TITLE
GUI Freeze While OMX.broadcom.video_decode - OMX_ErrorInsufficientResources, insufficient resources

### ISSUE THREAD

**Issue by benjaminwolf** [RasPlex/RasPlex#507]
Had a GUI freeze up while attempting to play a file. Was able to SSH in and snatch the logs and reboot from the software, so only the GUI was unresponsive. Appears to have entered a loop condition when the Video Decoder ran out of resources. See attached log excerpt.

I've included the media information below. The item played fine immediately after a reboot. Rasplex/OpenPHT had been working fine for days without reboot before this loop condition.

HW: rPi3 w/ 2.5a 5v Powersupply
SW: Rasplex/OpenPHT 1.6.0
PMS: 0.9.17.2.2159-2bd156c :: Windows 2012 R2
ENV: Local PMS hardlined to rPi3 hardline connection. Settings were for DirectPlay.

[LOGS]
[plexhometheater.zip](https://github.com/RasPlex/RasPlex/files/317674/plexhometheater.zip)
[pht_excerpt.txt](https://github.com/RasPlex/RasPlex/files/317675/pht_excerpt.txt)

[PMS Media Info XML]
[2527.zip](https://github.com/RasPlex/RasPlex/files/317680/2527.zip)

[PMS Media Info]
> Media
> 
>     Video Resolution 1080p
>     Duration 1:01:37
>     Bitrate 10160 kbps
>     Width 1920
>     Height 1080
>     Aspect Ratio 1.78
>     Container MKV
>     Video Frame Rate 24p
>     Audio Profile dts
>     Video Profile high
> 
> Part
> 
>     Duration 1:01:37
>     Filename.mkv
>     Size 4.37 GB
>     Audio Profile dts
>     Container MKV
>     Indexes sd
>     Video Profile high
> 
>     Codec H264
>     Bitrate 8648 kbps
>     Language English
>     Bit Depth 8
>     CABAC true
>     Chroma Subsampling 4:2:0
>     Duration 1:01:37
>     Frame Rate 23.976 fps
>     Frame Rate Mode cfr
>     Header Stripping true
>     Height 1080
>     Level 4.0
>     Pixel Format yuv420p
>     Profile high
>     Ref Frames 4
>     Scan Type progressive
>     Width 1920
> 
>     Codec DCA
>     Channels 5.1
>     Bitrate 1509 kbps
>     Language English
>     Audio Channel Layout 5.1(side)
>     Bit Depth 24
>     Bitrate Mode CBR
>     Duration 1:01:37
>     Profile dts
>     Sampling Rate 48000 Hz
> 
>     Codec SRT
>     Language English
>     Format SRT
> 
>     Codec SRT
>     Language English
> 
>     Codec SRT
>     Language English
> 
>     Codec SRT
>     Language English

[MediaArea.net/MediaInfo]
> General
> Unique ID                                : 
> Complete name                            : D:\0\medianame.mkv
> Format                                   : Matroska
> Format version                           : Version 4 / Version 2
> File size                                : 3.71 GiB
> Duration                                 : 49mn 58s
> Overall bit rate                         : 10.6 Mbps
> Encoded date                             : UTC 2016-04-25 04:20:12
> Writing application                      : mkvmerge v7.0.0 ('Where We Going') 64bit built on Jun 22 2014 08:19:39
> Writing library                          : libebml v1.3.0 + libmatroska v1.4.1
> 
> Video
> ID                                       : 1
> Format                                   : AVC
> Format/Info                              : Advanced Video Codec
> Format profile                           : High@L4.1
> Format settings, CABAC                   : Yes
> Format settings, ReFrames                : 4 frames
> Codec ID                                 : V_MPEG4/ISO/AVC
> Duration                                 : 49mn 58s
> Bit rate                                 : 10.0 Mbps
> Width                                    : 1 920 pixels
> Height                                   : 1 078 pixels
> Display aspect ratio                     : 16:9
> Frame rate mode                          : Constant
> Frame rate                               : 23.976 (24000/1001) fps
> Color space                              : YUV
> Chroma subsampling                       : 4:2:0
> Bit depth                                : 8 bits
> Scan type                                : Progressive
> Bits/(Pixel*Frame)                       : 0.202
> Stream size                              : 3.50 GiB (94%)
> Writing library                          : x264 core 148 r2665+53 6629127 t_mod_Custom [8-bit@all X86_64]
> Encoding settings                        : cabac=1 / ref=4 / deblock=1:-3:-3 / analyse=0x3:0x113 / me=umh / subme=11 / psy=1 / fade_compensate=0.00 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=32 / chroma_me=1 / trellis=2 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=0 / chroma_qp_offset=-2 / threads=24 / lookahead_threads=4 / sliced_threads=0 / nr=0 / decimate=0 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / fgo=0 / bframes=8 / b_pyramid=2 / b_adapt=2 / b_bias=0 / direct=3 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=23 / scenecut=40 / intra_refresh=0 / rc_lookahead=60 / rc=crf / mbtree=0 / crf=17.0000 / qcomp=0.60 / qpmin=0:0:0 / qpmax=69:69:69 / qpstep=4 / vbv_maxrate=62500 / vbv_bufsize=78125 / crf_max=0.0 / nal_hrd=none / filler=0 / ip_ratio=1.40 / pb_ratio=1.30 / aq=3:0.80 / aq-sensitivity=10.00 / aq-factor=1.00:1.00:1.00 / aq2=0 / aq3=0
> Default                                  : Yes
> Forced                                   : No
> Color range                              : Limited
> Matrix coefficients                      : BT.709
> 
> Audio
> ID                                       : 2
> Format                                   : AC-3
> Format/Info                              : Audio Coding 3
> Mode extension                           : CM (complete main)
> Format settings, Endianness              : Big
> Codec ID                                 : A_AC3
> Duration                                 : 49mn 58s
> Bit rate mode                            : Constant
> Bit rate                                 : 384 Kbps
> Channel(s)                               : 6 channels
> Channel positions                        : Front: L C R, Side: L R, LFE
> Sampling rate                            : 48.0 KHz
> Frame rate                               : 31.250 fps (1536 spf)
> Compression mode                         : Lossy
> Stream size                              : 137 MiB (4%)
> Default                                  : Yes
> Forced                                   : No

**Comment by NedtheNerd** [comment]
Can you check in newly released 1.6.1 and advise.

**Comment by benjaminwolf** [comment]
Don't know if I can force the condition to happen. I ran the same file again, but without getting back into the condition. That's to be expected though, as after rebooting the PI the first time, it did not fall into the same condition. Not sure this is something that can be tested for easily.

**Comment by NedtheNerd** [comment]
OK, thanks, I'll close this for now, if it happens in the future please feel free to reopen with further comment.
