### ISSUE TITLE
Playlist not showing up after server update

### ISSUE THREAD

**Issue by rubix45** [RasPlex/RasPlex#514]
I just updated my plex server to Version 1.0.0.2261 and when i went to my rasplex devises, either running Version 1.6.1 or Version 1.0.3, none of my playlists would show up.  

I tried looking for settings on the server and on the Rasplex device.  i have also tried logging out of the device and logging back in.    I also tried creating a new playlist but that one did not show up either.

Anyone got any ideas?

**Comment by Kwiboo** [comment]
This is a known issue and are being worked on, see forums.plex.tv/discussion/222663/important-information-playlists-broken-with-pms-1-0-0/p1

**Comment by rubix45** [comment]
Thank you Kwidoo.  I will look for the update when it comes.  you are AWESOME!!

**Comment by NedtheNerd** [comment]
Fixed in next release - 1.6.2, closing issue.
