### ISSUE TITLE
rasplex name in IOS App & plexserver

### ISSUE THREAD

**Issue by tropas2001** [RasPlex/RasPlex#522]
I've got a number of rasplex devices which all report to the IOS plex app as "Rasplex & Rasplex" despite them having different hostnames under preferences. Plex server shows these all as RasPlex 

RPI3
plexmediaserver Version 1 on debian
Ethernet
Plex IOS app - 4.2

**Comment by NedtheNerd** [comment]
You need to set the nam in System Settings, System, System name and Preferences, System, Services, Device name.

Closing issue.
