### ISSUE TITLE
FR: Don't show episode thumbnail when unseen

### ISSUE THREAD

**Issue by Ruvetuve** [RasPlex/RasPlex#524]
Feature is present in RasPlex, Preferences > Skin settings > libraries > hide thumbnails for unwatched/in progress episodes.

FR can be closed, sry.

> I know this feature is in the Plex Black Edition template, i would love to see it in RasPlex itself.
> 
> Requesting for an option in the settings which can turn of the episodes thumbnails of unseen episodes. This is the screen where you can start the episode for playback. I get allot of spoilers before i can see the episode from this single image.
> 
> Let me know if this is possible/wanted or unwanted.
> 
> Keep up the good work, thanks!

**Comment by NedtheNerd** [comment]
This functionality was included in the default skin in release 1.6.1, closing issue.
