### ISSUE TITLE
Typo in transcoding message

### ISSUE THREAD

**Issue by artbatista** [RasPlex/RasPlex#530]
**RPi model**: Raspberry Pi 1
**RasPlex**: 1.6.2 default skin
**PMS**: 1.00
**Network**: Ethernet

There is a typo. When a video file resolution is too large and PHT shows the transcoding  message, its something like this:

" Transcoding, video resolution to large"

It should be:

"Transcoding, video resolution **too** large"

**Comment by bkury** [comment]
fixed, thanks for reporting ....

https://github.com/bkury/OpenPHT/commit/f61049f7260c453727e86e91979e97e50d454a07
