### ISSUE TITLE
feature request: moonlight integration

### ISSUE THREAD

**Issue by bellinger61** [RasPlex/RasPlex#537]
I don't know how easy it would be to accomplish but it looks like a version of moonlight has been modified to work with openelec and I think would put rasplex light years ahead of other media center options for the rpi please see link below for github depository

https://github.com/dead/moonlight-openelec-rpi2

**Comment by vampywiz17** [comment]
+1

**Comment by bkury** [comment]
This is currently not possible because OpenPHT lacks python/addon support, already discussed here :
http://forums.plex.tv/discussion/242341/odroid-c2-with-openpht-including-luna-and-moonlight
