### ISSUE TITLE
Request: Camera board support 

### ISSUE THREAD

**Issue by Nanodk** [RasPlex/RasPlex#541]
RPi model: RPi 3 B v1.2
RasPlex: 1.6.2.123-e23a7eef
PMS: 1.2.2.2857 / Win 10 pro
Network: Ethernet

Cam Board support would be great, since the RP is always on (well mine is) it could add to the in-house security as a Nanny Cam/Security Cam. Nothing fancy just a option for on or off, a streaming URL:Port and the working as a IP-cam. Possible? hope so.

**Comment by dalehamel** [comment]
out of scope
