### ISSUE TITLE
Back button not working on remote, must use delete key.

### ISSUE THREAD

**Issue by mindspies** [RasPlex/RasPlex#547]
The issue is with Raspberry Pie 3.  With Raspberry Pie 2 I don't have that problem.  I have a multifunction remote controller with keyboard and airmouse and the back (home) button is not working.  I must use the delete key of the keyboard to achieve the same function.  I've tried reinstalling Rasplex and with different version.  Same thing.  Tree different remote, same thing.

Any clue? Thanks.

**Comment by benjaminwolf** [comment]
I'm guessing you have/had a keyboard remapping on your rPi2 that is missing from your rPi3. They are identical in their compatibility with airmouse/keyboards.
