### ISSUE TITLE
Doesn't support the lastest Synology Plex Media Server(version: 1.3.3.3148)

### ISSUE THREAD

**Issue by goxofy** [RasPlex/RasPlex#552]
My Plex Media Server is running on a Synology NAS and the version is 1.3.3.3148(lastest), but I can't get any media info in the RasPlex. When I downgraded version to  0.9.16.3 the RasPlex could find the media from the Plex Media Server.

**RPi model**: raspi 2
**RasPlex**: 1.7.1
**PMS**: 1.3.3.3148
**Network**: either

**Comment by g1t-dlanor** [comment]
If you've recently upgraded from that older PMS version to the current one, then I urge you to doublecheck all the server settings, as some features have been added/modified in newer versions and the new default settings may not be appropriate for your setup.

Also, I'm not entirely sure of what you mean by "can't get any media info". It could mean that RasPlex gets no connection at all to your PMS, but it could also mean that it does connect and get a full media listing, just lacking all detailed media info, or anything in between these variants. I suspect the first variant is more true, but please describe your problem in greater detail so we'll know for sure.

Another thing we'd like to know is if you've successfully used any other Plex clients (on PC/Android/iOS) with the new PMS version, so we can rule out any problems with the functionality of that server as such.

**Comment by goxofy** [comment]
Hello, dlanor

Thank you very much for reply.

I have checked the settings in the newest PMS and there is nothing different from the older one.

And I'm not sure whether the RasPlex gets connection to my PMS, I have specified the PMS ip:port in the RasPlex settings but the RasPlex can't get anything from the PMS, no media listing. no details. I suspect that  the RasPlex doesn't get connection to my PMS.

And the third thing, I have successfully used many clients with my PMS, including iOS, Web and Android(on the Xiaomi TV Box), so I think my PMS is ok.

Thank you very much!

Tink

**Comment by Kwiboo** [comment]
@goxofy when using newer PMS versions you will need to sign-in to RasPlex (same as any other Plex client) or add your local network to the `List of IP addresses and networks that are allowed without auth` server setting

**Comment by goxofy** [comment]
@Kwiboo Thank you!

Can you tell me how I can add local network to the "List of IP addresses and networks that are allowed without auth" server setting, I cant find this setting on my PMS.

**Comment by goxofy** [comment]
@Kwiboo Thank you very much!

It works!
