### ISSUE TITLE
HUNGARY LANG ERROR

### ISSUE THREAD

**Issue by angel228282** [RasPlex/RasPlex#560]
Please look at the pictures:
`
http://i64.tinypic.com/24lvr7o.jpg
http://i64.tinypic.com/2ry4jev.jpg
http://i63.tinypic.com/2ef2gau.jpg
http://i63.tinypic.com/8zg2mc.jpg

`
Green: Hungarian
Red: English

**RPi model**:  PI2
**OPENPHT**: this error on

**RasPlex**: 1.7.1
**PMS**:  2.6.1 (gentoo)
**Network**: ethernet

**Comment by angel228282** [comment]
Openpht it is the failure of Hungarian language!

**Comment by dalehamel** [comment]
Feel free to submit Hungarian translations in a pull request
