### ISSUE TITLE
HDMI-CEC Quirks: Stuck in menus.

### ISSUE THREAD

**Issue by svein83** [RasPlex/RasPlex#563]
If you use HDMI-CEC to control RasPlex, there's no way to exit the preferences menu. The "Back" or "Exit" buttons on the remote won't work with OpenELEC or Kodi either... This menu could have an exit button as a workaround.

Upon further testing: There are more menus with no way to exit them with a tv remote over CEC.

**This distro is unusable with only a TV-remote**, since when you open a title's info screen you can move the selection up and down on the left side menu, and you can play the title, but there's no way to go back to the library or back to home!

It's too bad, because I like the responsiveness and all the posibillities, but it looks like I'll have to ditch RasPlex for someting that actually works with CEC.

**RPi model**: All
**RasPlex**: All
**PMS**: All
**Network**: All

**Comment by chadberg** [comment]
This is likely to have more to do with your remote. If your remote does not have a 'return' or 'back' button you may find yourself in this circumstance. My tv remote includes a return button which works fine to return from these menus.

**Comment by svein83** [comment]
Okay...

It does... It has a back/return button, an exit button, and a cancel
button...

23. des. 2017 2:52 a.m. skrev "Chad Bergeron" <notifications@github.com>:
