### ISSUE TITLE
[Question] Using RasPlex without Plex.tv account?

### ISSUE THREAD

**Issue by ghost** [RasPlex/RasPlex#607]
Hi all,

I have plex server on my nas but it is not claim and I don't want use any account on plex.tv.
Is it possible to use RasPlex without connecting to Plex.tv account? Just enter ip of my nas without login to plex.tv?

Thanks

**Comment by dalehamel** [comment]
You might have issues discovering your media server this way, but you should be able to go into preferences and specify the server URL manually.

plex.tv helps with the discovery aspect, I would suggest you consider using it unless you have a really good reason not to.
