### ISSUE TITLE
Rasplex on rpi3b+

### ISSUE THREAD

**Issue by therudy** [RasPlex/RasPlex#620]
Hello ! :-)

Does anyone have information about when rasplex stable version will be posted for raspberry pi 3b+ ? 

@dalehamel  thank in advance :-)

**Comment by dalehamel** [comment]
Hi, https://github.com/RasPlex/RasPlex/issues/606 is an existing issue so I'm closing this as a duplicate. 

Regarding the last update in that issue, I haven't finished getting my testing lab up and running but am close.
