### ISSUE TITLE
Project seems dead, how to progress?

### ISSUE THREAD

**Issue by ohhai-kthxbai** [RasPlex/RasPlex#637]
It would seem that @dalehamel and @Kwiboo can't/aren't maintaining this anymore (no judgement!). Is it even possible to create new rasplex builds given the resources here? What skills are required? OS compiling? Scripting? What language(s) is OpenPHT/rasplex written in?

Clearly I'm not a dev, but I know a few and would like to know what/who to recruit!

Specifically I'm after a build that supports Pi4 (h.265/HEVC) and Wireguard.

**Comment by dalehamel** [comment]
These sorts of issues aren’t helpful
