### ISSUE TITLE
remote server not working

### ISSUE THREAD

**Issue by nightmare04** [RasPlex/RasPlex#650]
Remote server stop working 1 october, reinstall image with version 1.8.0B, still not working.
RPi model: RPi B+
RasPlex: 1.8.0b
PMS: RasPlex 1.8.0.0 573b6d73
Network: ethernet
![IMG_7258](https://user-images.githubusercontent.com/23357213/135755873-e2164171-f7a2-4d20-ad68-2bdca74e9d6a.jpg)
![IMG_7257](https://user-images.githubusercontent.com/23357213/135755880-f5737b39-4ea5-46d4-9a31-6eb80b50726e.jpg)

**Comment by dalehamel** [comment]
Have you signed in?

**Comment by nightmare04** [comment]
> Have you signed in?

Yes, try add local server manual - not working

**Comment by dalehamel** [comment]
If you are on the new images (https://github.com/RasPlex/RasPlex/releases/tag/1.8.0b) it is probably not an SSL issue like in #645 , but try setting "Secure connections" to "disabled" on the server like in https://github.com/RasPlex/RasPlex/issues/645#issuecomment-932298511

I can't really be much help beyond this though

**Comment by nightmare04** [comment]
> If you are on the new images (https://github.com/RasPlex/RasPlex/releases/tag/1.8.0b) it is probably not an SSL issue like in #645 , but try setting "Secure connections" to "disabled" on the server like in [#645 (comment)](https://github.com/RasPlex/RasPlex/issues/645#issuecomment-932298511)
> 
> I can't really be much help beyond this though

Thnx, with "Secure connections" to "disabled" work

**Comment by dalehamel** [comment]
That's very weird, the updated SSL certificate authority should make that not be necessary. Perhaps it is a server-side issue

**Comment by ark626** [comment]
YOu have to delete the cached certificate in the Server.
Now go to the plex server and fix the cached cert:

```
Browse to the Plex Media Server data directory on your server (https://support.plex.tv/articles/202915258-where-is-the-plex-media-server-data-directory-located/)
Open the Cache folder
Delete cert-v2.p12
Restart Plex Media Server
```
