### ISSUE TITLE
1.8.0-b pi3 image does not boot

### ISSUE THREAD

**Issue by thebino** [RasPlex/RasPlex#651]
@dalehamel Thanks a lot for the latest fix <3

I flashed the [RasPlex-1.8.0.0b-573b6d73-RPi3bplus.arm.img.gz](https://github.com/RasPlex/RasPlex/releases/download/1.8.0b/RasPlex-1.8.0.0b-573b6d73-RPi3bplus.arm.img.gz) to my sd-card and the pi does not boot.
Checked shasum and tried another download. No change

**I installed the [RasPlex-1.8.0b.148-573b6d73-RPi2.arm.img.gz](https://github.com/RasPlex/RasPlex/releases/download/1.8.0b/RasPlex-1.8.0b.148-573b6d73-RPi2.arm.img.gz) and everything works like a charm.**

**RPi model**: Raspberry PI 3 Model b
**RasPlex**: 1.8.0-b
**PMS**: [version and operating system]
**Network**: wifi

**Comment by dalehamel** [comment]
@thebino there is a separate raspberry pi called the 3b *plus*, it is different than the 3b. 

Confusingly, 3b uses the image for the raspberry pi 2, but 3b+ needs a different image. This is why 3b+ did not work for you, because you have a 3b.
